name: terracotta
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - numpy
  - rasterio>=1.3.0
  - shapely
  - pip
  - pip:
    - crick
    - psycopg2-binary
    - -e .[recommended]
