root: true
extends:
  - 'airbnb-typescript'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'eslint-plugin-import'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  tsconfigRootDir: '.'
env:
  browser: true
  node: true
rules:
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars': 'warn'