name: Build client app

on:
  pull_request:
    paths:
      - "terracotta/client/app/**"

  push:
    branches:
      - main
    paths:
      - "terracotta/client/app/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build app
        run: |
          yarn install --frozen-lockfile
          yarn build
        working-directory: terracotta/client/app

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.0
        with:
          commit_message: "[skip ci] Commit latest build"
