name: Upload release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/terracotta
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # make sure tags are fetched so we can get a version
      - run: |
          git fetch --prune --unshallow --tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build sdist
        run: |
          python setup.py sdist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
